services:
  # Database
  taskspree-db:
    image: postgres:17-alpine
    container_name: taskspree-db
    environment:
      - POSTGRES_DB=taskspree
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - taskspree_data:/var/lib/postgresql/data

  taskspree-redis:
    image: redis:alpine
    container_name: taskspree-redis
    ports:
      - "6379:6379"

volumes:
  taskspree_data: